version: '3.9'

services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  frontend:
    build: .
    ports:
      - "3000:3000"

  api_server:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args:
        - REDIS_URL=${REDIS_URL}
    command: ["/dex_backend_runtime/api_server"]
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      
  grpc_server:
    build: ./backend
    command: ["/dex_backend_runtime/grpc_server"]
    ports:
      - "50051:50051"
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  metrics_worker:
    build: ./backend
    command: ["/dex_backend_runtime/metrics_worker"]
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  ohlcv_worker:
    build: ./backend
    command: ["/dex_backend_runtime/ohlcv_worker"]
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  txn_worker:
    build: ./backend
    command: ["/dex_backend_runtime/txn_worker"]
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  metrics_service:
    build: ./backend
    command: ["/dex_backend_runtime/metrics_service"]
    env_file:
      - ./backend/.env
    depends_on:
      - redis

volumes:
  redis_data: