[package]
name = "grpc-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.99"
dotenvy = "0.15.7"
futures = "0.3.31"
tokio = { version = "1.46.1", features = ["full"] }
yellowstone-grpc-client = "8.0.0"
yellowstone-grpc-proto = "8.0.0"
